### ISSUE TITLE
Donate?

### ISSUE THREAD

**Issue by lectrode** [sen87/CNTP#2]
I've been using your CNTP project for quite some time now on a daily basis and would like to give back, even if it's not much.

Do you accept donations?

**Comment by sen87** [comment]
Hi lectrode, sry for the late reply!

Hearing that you like the project and find it useful is already enough for me. I've created it in my free time and won't monetize it in any way.

The only thing I pay for is the server bill. If you want to help with that you can do so via PayPal (sen@archlinux.us). Thank you!
